### ISSUE TITLE
Dart sim on Bullseye

### ISSUE THREAD

**Issue by abhishekranaji** [dartsim/dart-debian#8]
Hi,
I would like to install DART on debian 11 arm64 
I am not getting hint how to do so
Can anyone help me out

Thank you

**Comment by jslee02** [comment]
Hello, DART offers binary packages for several package managers, but as far as I know, it doesn't provide packages directly for Debian. I'm not a Debian expert, but since Debian and Ubuntu share many packages, you might be able to use the Ubuntu package (via apt-get or a PPA) on Debian (not sure though). Alternatively, as a last resort, you can always build DART from source. You can find instructions in the documentation: https://dartsim.github.io/install_dart_on_ubuntu.html
